[package]
name = "raytracer"
version = "0.1.0"
authors = ["Advay Pal <advaypal@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rand = "0.7.3"
